name: Build Pocket Poster IPA

on:
 
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 【修改点】强制使用服务器目前支持的 16.4.0 版本
      - name: Set up Xcode environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4.0' 

      - name: Make Build Script Executable
        run: chmod +x ./ipabuild.sh 

      - name: Run IPA Build Script (Release)
        run: ./ipabuild.sh 

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pocket-Poster-IPA 
          path: build/*.ipa 
          retention-days: 7
