name: Build Pocket Poster IPA

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 【修改点】自动切换并使用当前系统自带的最新稳定版 Xcode 环境
      - name: Set up latest Xcode environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable' 

      - name: Make Build Script Executable
        run: chmod +x ./ipabuild.sh 

      - name: Run IPA Build Script (Release)
        run: ./ipabuild.sh 

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pocket-Poster-IPA 
          path: build/*.ipa 
          retention-days: 7
